# Generated by Django 4.2.6 on 2023-10-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
