# Generated by Django 4.2.6 on 2023-10-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_usersurvey_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='usersurvey',
            options={'verbose_name': 'Просмотренный опрос', 'verbose_name_plural': 'Просмотренные опросы'},
        ),
    ]
