# Generated by Django 4.2.6 on 2023-10-26 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0010_watchedsurvey_alter_survey_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedsurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='survey.survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='watchedsurvey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
