# Generated by Django 4.2.6 on 2023-10-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_choice_question_answer_delete_answer_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='published_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Время публикации'),
        ),
    ]
